server:
  port: 8088
  servlet:
    context-path: /school
spring:
  application:
    name: school
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@${DB_URL}
    # p6spy, output consume time, don't use at production environment
    # driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    # url: jdbc:p6spy:oracle:thin:@${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
      idle-timeout: 600000
      auto-commit: true
      pool-name: hikaricppool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  profiles:
    active: dev
logging:
  file:
    name: /tmp/logs/school.log
  level:
    org.springframework.web: DEBUG
mybatis:
  type-aliases-package: site.k8scloud.school.entity # entity class path
  mapper-locations: classpath:mapper/*.xml
# logging, don't use at production environment
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted  #全局逻辑删除字段值
